name: Docker Build

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.architecture }}-${{ github.sha }}
          cache-from: type=gha,repository=ghcr.io/${{ github.repository }}
          cache-to: type=gha,repository=ghcr.io/${{ github.repository }}
          cache-bypass: false
          build-args: |
            REACT_APP_ARCHITECTURE=${{ matrix.architecture }}
          platforms: ${{ matrix.architecture }}
